export enum TileForm{
    empty,
    floor,
    wallBottom,
    wallBottomLeft,
    wallLeft,
    wallTopLeft,
    wallTop,
    wallTopRight,
    wallRight,
    wallBottomRight,
    wallOuterBottomLeft,
    wallOuterTopLeft,
    wallOuterTopRight,
    wallOuterBottomRight,
    crossroads,
    path,
    turn,
    threeWay,
    threeWayTurnOnly,
    turnBack,
    specialTurn,
    specialThreeWay,
    specialThreeWayTurnOnly,
    specialThreeWayForced,
}
export const walls = [TileForm.wallBottom,TileForm.wallBottomLeft,TileForm.wallLeft,TileForm.wallTopLeft,TileForm.wallTop,TileForm.wallTopRight,TileForm.wallRight,TileForm.wallBottomRight,TileForm.wallOuterBottomLeft,TileForm.wallOuterTopLeft,TileForm.wallOuterTopRight,TileForm.wallOuterBottomRight];
